CREATE TABLE IF NOT EXISTS payroll.salary_component ( -- this assumes that fixed and gross components remain the same for all employees in the company
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL, -- verify with Income Tax Manual
	CHECK(name IN('Basic Salary','Home Rent Allowance','Festival Bonus','Car Maintenance Allowance','Mobile Bill','Entertainment Allowance','Convenyance Allowance','Overtime Pay','Lunch Subsidy','Employee contribution to PF')),
	is_fixed BOOLEAN DEFAULT TRUE, -- if not fixed, then variable
	description TEXT,
	company_id INTEGER REFERENCES company.company(id)
);

CREATE TABLE IF NOT EXISTS payroll.employee_f_salary (
	id SERIAL PRIMARY KEY,
	employee_id uuid REFERENCES employee.employee(id),
	salary_component_id INTEGER REFERENCES payroll.salary_component(id),
	effective_from DATE NOT NULL,
	effective_till DATE,
	amount DECIMAL(10,2) NOT NULL,
	is_active BOOLEAN DEFAULT TRUE NOT NULL, -- this component hits / impacts the payslip of the employee 
	is_current BOOLEAN DEFAULT TRUE, -- current means will be paid now; later means to be paid later like Provident Fund 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP, -- on update
	company_id INTEGER REFERENCES company.company(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS payroll.employee_v_salary (
	id SERIAL PRIMARY KEY,
	employee_id uuid REFERENCES employee.employee(id),
	salary_component_id INTEGER REFERENCES payroll.salary_component(id),
	amount DECIMAL(10,2) NOT NULL,
	payment_month DATE NOT NULL, -- record the month on which it is going to be hit the payslip
	is_current BOOLEAN DEFAULT TRUE, -- some portion of variable pay can be held back like Profit Share, this gets accumulated over the years
	remark VARCHAR(200), -- write down the occasion like Profit Share, Festival Bonus, Commission
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP,
	company_id INTEGER REFERENCES company.company(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS payroll.employee_salary_record (
	id SERIAL PRIMARY KEY,
	employee_id uuid REFERENCES employee.employee(id),
	which_month DATE NOT NULL, -- format the month from front-end UI
	which_year DATE NOT NULL, -- format the year from front-end UI
	gross_salary INT NOT NULL, -- Gross Salary = f_salary (c+l) + v_salary (c+l)
	tds INT NOT NULL, -- Tax Deductible at source
	net_salary INT NOT NULL, -- Net Payable Salary / Net Receipt this month = f_salary(c) + v_salary(c) - TDS
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- auto generated by the last week of the month
	updated_at TIMESTAMP,
	approved_by_id uuid REFERENCES employee.employee(id) NOT NULL,
	company_id INTEGER REFERENCES company.company(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS payroll.disbursement (
	id SERIAL PRIMARY KEY,
	employee_id uuid REFERENCES employee.employee(id) NOT NULL,
	salary_record_id INTEGER REFERENCES payroll.employee_salary_record(id) NOT NULL,
	is_disbursed BOOLEAN DEFAULT TRUE NOT NULL,
	transaction_date DATE NOT NULL,
	payment_method_id INTEGER REFERENCES transaction.payment_method(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP,
	company_id INTEGER REFERENCES company.company(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS payroll.salary_accumulation ( -- if is_current = FALSE (Fixed + Variable), the amount gets accumulated over the years || Automatically creates a record when f & v (l) becomes due
	id SERIAL PRIMARY KEY,
	variable_salary_id INTEGER REFERENCES payroll.employee_v_salary(id) NOT NULL,
	fixed_salalry_id INTEGER REFERENCES payroll.employee_f_salary(id) NOT NULL,
	net_balance INTEGER NOT NULL, -- accumulation of f_salary(l) & v_salary(l) till date
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP,
	employee_id uuid REFERENCES employee.employee(id) NOT NULL,
	company_id INTEGER REFERENCES company.company(id) NOT NULL
);